- name: Deploy configuration files
  become: true
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart_mysql
  with_items:
    - etc/mysql/mysql.conf.d/mysqld.cnf
