- name: Deploy public keys
  hosts: servers
  user: ubuntu
  tasks:
    - name: Deploy authorized_keys
      become: true
      become_user: isucon
      become_method: sudo
      ansible.builtin.copy:
        src: ./authorized_keys
        dest: /home/isucon/.ssh/authorized_keys
        # dest: /home/isucon/.ssh/authorized_keys_{{ansible_date_time.epoch}}.bak
        owner: isucon
        group: isucon
        mode: "0600"
        backup: true
