- name: Deploy public keys
  hosts: servers
  user: ubuntu
  vars_files:
    - var.yaml
  tasks:
    - name: Set key authorized keys
      become: true
      become_user: isucon
      become_method: sudo
      ansible.posix.authorized_key:
        user: isucon
        state: present
        key: "{{ item.key }}"
      with_items:
        - "{{ keys }}"
