version: '3.8'

services:
  db:
    container_name: "isucon-db"
    build:
      context: docker
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  